from process_running_state.petri_net import PetriNet


def _petri_net_with_AND_and_nested_XOR() -> PetriNet:
    petri_net = PetriNet()
    petri_net._cached_search = False
    petri_net.add_place("0", "p0")
    petri_net.add_place("2", "p2")
    petri_net.add_place("4", "p4")
    petri_net.add_place("5", "p5")
    petri_net.add_place("8", "p8")
    petri_net.add_place("9", "p9")
    petri_net.add_place("13", "p13")
    petri_net.add_place("14", "p14")
    petri_net.add_place("17", "p17")
    petri_net.add_place("18", "p18")
    petri_net.add_place("19", "p19")
    petri_net.add_place("00", "p00")
    petri_net.add_place("23", "p23")
    petri_net.add_place("25", "p25")
    petri_net.add_place("27", "p27")
    petri_net.add_place("29", "p29")
    petri_net.add_transition("1", "A")
    petri_net.add_transition("10", "B")
    petri_net.add_transition("15", "C")
    petri_net.add_transition("16", "D")
    petri_net.add_transition("24", "E")
    petri_net.add_transition("28", "F")
    petri_net.add_transition("3", "silent_3", invisible=True)
    petri_net.add_transition("6", "silent_6", invisible=True)
    petri_net.add_transition("7", "silent_7", invisible=True)
    petri_net.add_transition("11", "silent_11", invisible=True)
    petri_net.add_transition("12", "silent_12", invisible=True)
    petri_net.add_transition("20", "silent_20", invisible=True)
    petri_net.add_transition("21", "silent_21", invisible=True)
    petri_net.add_transition("22", "silent_22", invisible=True)
    petri_net.add_transition("26", "silent_26", invisible=True)
    petri_net.add_edge("0", "1")
    petri_net.add_edge("1", "2")
    petri_net.add_edge("2", "3")
    petri_net.add_edge("3", "4")
    petri_net.add_edge("3", "5")
    petri_net.add_edge("4", "6")
    petri_net.add_edge("4", "7")
    petri_net.add_edge("6", "8")
    petri_net.add_edge("7", "9")
    petri_net.add_edge("8", "10")
    petri_net.add_edge("9", "11")
    petri_net.add_edge("9", "12")
    petri_net.add_edge("11", "13")
    petri_net.add_edge("12", "14")
    petri_net.add_edge("13", "15")
    petri_net.add_edge("14", "16")
    petri_net.add_edge("10", "17")
    petri_net.add_edge("15", "18")
    petri_net.add_edge("16", "19")
    petri_net.add_edge("17", "20")
    petri_net.add_edge("18", "21")
    petri_net.add_edge("19", "22")
    petri_net.add_edge("20", "23")
    petri_net.add_edge("21", "23")
    petri_net.add_edge("22", "23")
    petri_net.add_edge("5", "24")
    petri_net.add_edge("24", "25")
    petri_net.add_edge("23", "26")
    petri_net.add_edge("25", "26")
    petri_net.add_edge("26", "27")
    petri_net.add_edge("27", "28")
    petri_net.add_edge("28", "29")
    petri_net.initial_marking = {"0"}
    petri_net.final_marking = {"29"}
    return petri_net


def _petri_net_with_AND_and_nested_XOR_simple() -> PetriNet:
    petri_net = PetriNet()
    petri_net._cached_search = False
    petri_net.add_place("0", "p0")
    petri_net.add_place("2", "p2")
    petri_net.add_place("3", "p3")
    petri_net.add_place("8", "p8")
    petri_net.add_place("9", "p9")
    petri_net.add_place("11", "p11")
    petri_net.add_transition("1", "A")
    petri_net.add_transition("4", "B")
    petri_net.add_transition("5", "C")
    petri_net.add_transition("6", "D")
    petri_net.add_transition("7", "E")
    petri_net.add_transition("10", "F")
    petri_net.add_edge("0", "1")
    petri_net.add_edge("1", "2")
    petri_net.add_edge("1", "3")
    petri_net.add_edge("2", "4")
    petri_net.add_edge("2", "5")
    petri_net.add_edge("2", "6")
    petri_net.add_edge("3", "7")
    petri_net.add_edge("4", "8")
    petri_net.add_edge("5", "8")
    petri_net.add_edge("6", "8")
    petri_net.add_edge("7", "9")
    petri_net.add_edge("8", "10")
    petri_net.add_edge("9", "10")
    petri_net.add_edge("10", "11")
    petri_net.initial_marking = {"0"}
    petri_net.final_marking = {"11"}
    return petri_net
