from process_running_state.bpmn_model import BPMNModel, BPMNNodeType


def _bpmn_model_with_AND_and_XOR() -> BPMNModel:
    bpmn_model = BPMNModel()
    bpmn_model._cached_search = False
    bpmn_model.add_event(BPMNNodeType.START_EVENT, "0", "Start")
    bpmn_model.add_event(BPMNNodeType.END_EVENT, "24", "End")
    bpmn_model.add_task("2", "A")
    bpmn_model.add_task("7", "B")
    bpmn_model.add_task("8", "C")
    bpmn_model.add_task("16", "D")
    bpmn_model.add_task("17", "E")
    bpmn_model.add_task("22", "F")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "4", "AND-split")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "11", "AND-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "13", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "20", "XOR-join")
    bpmn_model.add_flow("1", "flow", "0", "2")
    bpmn_model.add_flow("3", "flow", "2", "4")
    bpmn_model.add_flow("5", "flow", "4", "7")
    bpmn_model.add_flow("6", "flow", "4", "8")
    bpmn_model.add_flow("9", "flow", "7", "11")
    bpmn_model.add_flow("10", "flow", "8", "11")
    bpmn_model.add_flow("12", "flow", "11", "13")
    bpmn_model.add_flow("14", "flow", "13", "16")
    bpmn_model.add_flow("15", "flow", "13", "17")
    bpmn_model.add_flow("18", "flow", "16", "20")
    bpmn_model.add_flow("19", "flow", "17", "20")
    bpmn_model.add_flow("21", "flow", "20", "22")
    bpmn_model.add_flow("23", "flow", "22", "24")
    return bpmn_model


def _bpmn_model_with_XOR_within_AND() -> BPMNModel:
    bpmn_model = BPMNModel()
    bpmn_model._cached_search = False
    bpmn_model.add_event(BPMNNodeType.START_EVENT, "0", "Start")
    bpmn_model.add_event(BPMNNodeType.END_EVENT, "39", "End")
    bpmn_model.add_task("2", "A")
    bpmn_model.add_task("17", "B")
    bpmn_model.add_task("18", "C")
    bpmn_model.add_task("19", "D")
    bpmn_model.add_task("20", "E")
    bpmn_model.add_task("21", "F")
    bpmn_model.add_task("22", "G")
    bpmn_model.add_task("37", "H")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "4", "AND-split")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "35", "AND-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "8", "XOR-split-1")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "9", "XOR-split-2")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "10", "XOR-split-3")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "29", "XOR-join-1")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "30", "XOR-join-2")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "31", "XOR-join-3")
    bpmn_model.add_flow("1", "flow", "0", "2")
    bpmn_model.add_flow("3", "flow", "2", "4")
    bpmn_model.add_flow("5", "flow", "4", "8")
    bpmn_model.add_flow("6", "flow", "4", "9")
    bpmn_model.add_flow("7", "flow", "4", "10")
    bpmn_model.add_flow("11", "flow", "8", "17")
    bpmn_model.add_flow("12", "flow", "8", "18")
    bpmn_model.add_flow("13", "flow", "9", "19")
    bpmn_model.add_flow("14", "flow", "9", "20")
    bpmn_model.add_flow("15", "flow", "10", "21")
    bpmn_model.add_flow("16", "flow", "10", "22")
    bpmn_model.add_flow("23", "flow", "17", "29")
    bpmn_model.add_flow("24", "flow", "18", "29")
    bpmn_model.add_flow("25", "flow", "19", "30")
    bpmn_model.add_flow("26", "flow", "20", "30")
    bpmn_model.add_flow("27", "flow", "21", "31")
    bpmn_model.add_flow("28", "flow", "22", "31")
    bpmn_model.add_flow("32", "flow", "29", "35")
    bpmn_model.add_flow("33", "flow", "30", "35")
    bpmn_model.add_flow("34", "flow", "31", "35")
    bpmn_model.add_flow("36", "flow", "35", "37")
    bpmn_model.add_flow("38", "flow", "37", "39")
    return bpmn_model


def _bpmn_model_with_AND_and_nested_XOR() -> BPMNModel:
    bpmn_model = BPMNModel()
    bpmn_model._cached_search = False
    bpmn_model.add_event(BPMNNodeType.START_EVENT, "0", "Start")
    bpmn_model.add_event(BPMNNodeType.END_EVENT, "25", "End")
    bpmn_model.add_task("2", "A")
    bpmn_model.add_task("10", "B")
    bpmn_model.add_task("14", "C")
    bpmn_model.add_task("15", "D")
    bpmn_model.add_task("19", "E")
    bpmn_model.add_task("23", "F")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "5", "AND-split")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "22", "AND-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "7", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "11", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "26", "XOR-join")
    bpmn_model.add_flow("1", "flow", "0", "2")
    bpmn_model.add_flow("3", "flow", "2", "5")
    bpmn_model.add_flow("4", "flow", "5", "7")
    bpmn_model.add_flow("6", "flow", "5", "19")
    bpmn_model.add_flow("8", "flow", "7", "10")
    bpmn_model.add_flow("9", "flow", "7", "11")
    bpmn_model.add_flow("12", "flow", "11", "14")
    bpmn_model.add_flow("13", "flow", "11", "15")
    bpmn_model.add_flow("16", "flow", "10", "26")
    bpmn_model.add_flow("17", "flow", "14", "26")
    bpmn_model.add_flow("18", "flow", "15", "26")
    bpmn_model.add_flow("20", "flow", "19", "22")
    bpmn_model.add_flow("21", "flow", "26", "22")
    bpmn_model.add_flow("27", "flow", "22", "23")
    bpmn_model.add_flow("24", "flow", "23", "25")
    return bpmn_model


def _bpmn_model_with_loop_inside_AND() -> BPMNModel:
    bpmn_model = BPMNModel()
    bpmn_model._cached_search = False
    bpmn_model.add_event(BPMNNodeType.START_EVENT, "0", "Start")
    bpmn_model.add_event(BPMNNodeType.END_EVENT, "20", "End")
    bpmn_model.add_task("2", "A")
    bpmn_model.add_task("10", "B")
    bpmn_model.add_task("8", "C")
    bpmn_model.add_task("18", "D")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "4", "AND-split")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "16", "AND-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "7", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "12", "XOR-join")
    bpmn_model.add_flow("1", "flow", "0", "2")
    bpmn_model.add_flow("3", "flow", "2", "4")
    bpmn_model.add_flow("5", "flow", "4", "7")
    bpmn_model.add_flow("6", "flow", "4", "8")
    bpmn_model.add_flow("9", "flow", "7", "10")
    bpmn_model.add_flow("11", "flow", "10", "12")
    bpmn_model.add_flow("13", "flow", "12", "7")
    bpmn_model.add_flow("14", "flow", "12", "16")
    bpmn_model.add_flow("15", "flow", "8", "16")
    bpmn_model.add_flow("17", "flow", "16", "18")
    bpmn_model.add_flow("19", "flow", "18", "20")
    return bpmn_model


def _bpmn_model_with_two_loops_inside_AND_followed_by_XOR_within_AND() -> BPMNModel:
    bpmn_model = BPMNModel()
    bpmn_model._cached_search = False
    bpmn_model.add_event(BPMNNodeType.START_EVENT, "0", "Start")
    bpmn_model.add_event(BPMNNodeType.END_EVENT, "46", "End")
    bpmn_model.add_task("2", "A")
    bpmn_model.add_task("11", "B")
    bpmn_model.add_task("12", "C")
    bpmn_model.add_task("32", "D")
    bpmn_model.add_task("33", "E")
    bpmn_model.add_task("34", "F")
    bpmn_model.add_task("35", "G")
    bpmn_model.add_task("44", "H")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "4", "AND-split")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "21", "AND-join")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "23", "AND-split")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "42", "AND-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "7", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "15", "XOR-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "8", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "16", "XOR-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "26", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "47", "XOR-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "27", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "48", "XOR-join")
    bpmn_model.add_flow("1", "flow", "0", "2")
    bpmn_model.add_flow("3", "flow", "2", "4")
    bpmn_model.add_flow("5", "flow", "4", "7")
    bpmn_model.add_flow("6", "flow", "4", "8")
    bpmn_model.add_flow("9", "flow", "7", "11")
    bpmn_model.add_flow("10", "flow", "8", "12")
    bpmn_model.add_flow("13", "flow", "11", "15")
    bpmn_model.add_flow("14", "flow", "12", "16")
    bpmn_model.add_flow("17", "flow", "15", "7")
    bpmn_model.add_flow("18", "flow", "16", "8")
    bpmn_model.add_flow("19", "flow", "15", "21")
    bpmn_model.add_flow("20", "flow", "16", "21")
    bpmn_model.add_flow("22", "flow", "21", "23")
    bpmn_model.add_flow("24", "flow", "23", "26")
    bpmn_model.add_flow("25", "flow", "23", "27")
    bpmn_model.add_flow("28", "flow", "26", "32")
    bpmn_model.add_flow("29", "flow", "26", "33")
    bpmn_model.add_flow("30", "flow", "27", "34")
    bpmn_model.add_flow("31", "flow", "27", "35")
    bpmn_model.add_flow("36", "flow", "32", "47")
    bpmn_model.add_flow("37", "flow", "33", "47")
    bpmn_model.add_flow("38", "flow", "34", "48")
    bpmn_model.add_flow("39", "flow", "35", "48")
    bpmn_model.add_flow("40", "flow", "47", "42")
    bpmn_model.add_flow("41", "flow", "48", "42")
    bpmn_model.add_flow("43", "flow", "42", "44")
    bpmn_model.add_flow("45", "flow", "44", "46")
    return bpmn_model


def _bpmn_model_with_three_loops_inside_AND_two_of_them_inside_sub_AND() -> BPMNModel:
    bpmn_model = BPMNModel()
    bpmn_model._cached_search = False
    bpmn_model.add_event(BPMNNodeType.START_EVENT, "0", "Start")
    bpmn_model.add_event(BPMNNodeType.END_EVENT, "39", "End")
    bpmn_model.add_task("5", "A")
    bpmn_model.add_task("15", "B")
    bpmn_model.add_task("16", "C")
    bpmn_model.add_task("27", "D")
    bpmn_model.add_task("32", "E")
    bpmn_model.add_task("37", "F")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "2", "AND-split")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "35", "AND-join")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "8", "AND-split")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "25", "AND-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "11", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "19", "XOR-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "12", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "20", "XOR-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "6", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "29", "XOR-join")
    bpmn_model.add_flow("1", "flow", "0", "2")
    bpmn_model.add_flow("3", "flow", "2", "5")
    bpmn_model.add_flow("4", "flow", "2", "6")
    bpmn_model.add_flow("7", "flow", "5", "8")
    bpmn_model.add_flow("9", "flow", "8", "11")
    bpmn_model.add_flow("10", "flow", "8", "12")
    bpmn_model.add_flow("13", "flow", "11", "15")
    bpmn_model.add_flow("14", "flow", "12", "16")
    bpmn_model.add_flow("17", "flow", "15", "19")
    bpmn_model.add_flow("18", "flow", "16", "20")
    bpmn_model.add_flow("21", "flow", "19", "11")
    bpmn_model.add_flow("22", "flow", "20", "12")
    bpmn_model.add_flow("23", "flow", "19", "25")
    bpmn_model.add_flow("24", "flow", "20", "25")
    bpmn_model.add_flow("31", "flow", "25", "32")
    bpmn_model.add_flow("26", "flow", "6", "27")
    bpmn_model.add_flow("28", "flow", "27", "29")
    bpmn_model.add_flow("30", "flow", "29", "6")
    bpmn_model.add_flow("33", "flow", "32", "35")
    bpmn_model.add_flow("34", "flow", "29", "35")
    bpmn_model.add_flow("36", "flow", "35", "37")
    bpmn_model.add_flow("38", "flow", "37", "39")
    return bpmn_model


def _bpmn_model_with_loop_inside_parallel_and_loop_all_back() -> BPMNModel:
    bpmn_model = BPMNModel()
    bpmn_model._cached_search = False
    bpmn_model.add_event(BPMNNodeType.START_EVENT, "0", "Start")
    bpmn_model.add_event(BPMNNodeType.END_EVENT, "25", "End")
    bpmn_model.add_task("2", "A")
    bpmn_model.add_task("11", "B")
    bpmn_model.add_task("15", "C")
    bpmn_model.add_task("23", "D")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "20", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "4", "XOR-join")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "8", "AND-split")
    bpmn_model.add_gateway(BPMNNodeType.PARALLEL_GATEWAY, "18", "AND-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "13", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "9", "XOR-join")
    bpmn_model.add_flow("1", "flow", "0", "2")
    bpmn_model.add_flow("3", "flow", "2", "4")
    bpmn_model.add_flow("5", "flow", "4", "8")
    bpmn_model.add_flow("6", "flow", "8", "9")
    bpmn_model.add_flow("7", "flow", "8", "15")
    bpmn_model.add_flow("10", "flow", "9", "11")
    bpmn_model.add_flow("12", "flow", "11", "13")
    bpmn_model.add_flow("14", "flow", "13", "9")
    bpmn_model.add_flow("16", "flow", "13", "18")
    bpmn_model.add_flow("17", "flow", "15", "18")
    bpmn_model.add_flow("19", "flow", "18", "20")
    bpmn_model.add_flow("21", "flow", "20", "4")
    bpmn_model.add_flow("22", "flow", "20", "23")
    bpmn_model.add_flow("24", "flow", "23", "25")
    return bpmn_model


def _bpmn_model_with_infinite_loop() -> BPMNModel:
    bpmn_model = BPMNModel()
    bpmn_model._cached_search = False
    bpmn_model.add_event(BPMNNodeType.START_EVENT, "0", "Start")
    bpmn_model.add_event(BPMNNodeType.END_EVENT, "18", "End")
    bpmn_model.add_task("2", "A")
    bpmn_model.add_task("8", "B")
    bpmn_model.add_task("16", "C")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "6", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "10", "XOR-join")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "13", "XOR-split")
    bpmn_model.add_gateway(BPMNNodeType.EXCLUSIVE_GATEWAY, "4", "XOR-join")
    bpmn_model.add_flow("1", "flow", "0", "2")
    bpmn_model.add_flow("3", "flow", "2", "4")
    bpmn_model.add_flow("5", "flow", "4", "6")
    bpmn_model.add_flow("7", "flow", "6", "8")
    bpmn_model.add_flow("9", "flow", "8", "10")
    bpmn_model.add_flow("11", "flow", "6", "10")
    bpmn_model.add_flow("12", "flow", "10", "13")
    bpmn_model.add_flow("14", "flow", "13", "4")
    bpmn_model.add_flow("15", "flow", "13", "16")
    bpmn_model.add_flow("17", "flow", "16", "18")
    return bpmn_model
